In [1]:
import xarray as xr
import climetlab as cml
import numpy as np

/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
template = cml.load_source("file", "/mnt/ssd2/Master/S2S_on_SFNO/inputs/ClimateInputData_202101010.grib")

In [4]:
for k, fs in enumerate(template):
    print("k: ", k,", fs: ", fs)

k:  0 , fs:  GribField(10u,None,20210101,0,0,0)
k:  1 , fs:  GribField(10v,None,20210101,0,0,0)
k:  2 , fs:  GribField(2t,None,20210101,0,0,0)
k:  3 , fs:  GribField(sp,None,20210101,0,0,0)
k:  4 , fs:  GribField(msl,None,20210101,0,0,0)
k:  5 , fs:  GribField(tcwv,None,20210101,0,0,0)
k:  6 , fs:  GribField(100u,None,20210101,0,0,0)
k:  7 , fs:  GribField(100v,None,20210101,0,0,0)
k:  8 , fs:  GribField(t,1000,20210101,0,0,0)
k:  9 , fs:  GribField(u,1000,20210101,0,0,0)
k:  10 , fs:  GribField(v,1000,20210101,0,0,0)
k:  11 , fs:  GribField(z,1000,20210101,0,0,0)
k:  12 , fs:  GribField(r,1000,20210101,0,0,0)
k:  13 , fs:  GribField(t,925,20210101,0,0,0)
k:  14 , fs:  GribField(u,925,20210101,0,0,0)
k:  15 , fs:  GribField(v,925,20210101,0,0,0)
k:  16 , fs:  GribField(z,925,20210101,0,0,0)
k:  17 , fs:  GribField(r,925,20210101,0,0,0)
k:  18 , fs:  GribField(t,850,20210101,0,0,0)
k:  19 , fs:  GribField(u,850,20210101,0,0,0)
k:  20 , fs:  GribField(v,850,20210101,0,0,0)
k:  21 , fs:  

In [3]:
tnc = template.to_xarray()

In [4]:
tnc.dims

Frozen({'number': 1, 'time': 1, 'step': 1, 'surface': 1, 'latitude': 721, 'longitude': 1440, 'isobaricInhPa': 13})

In [6]:
tnc.coords

Coordinates:
  * number         (number) int64 0
  * time           (time) datetime64[ns] 2021-01-01
  * step           (step) timedelta64[ns] 00:00:00
  * surface        (surface) float64 0.0
  * latitude       (latitude) float64 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude      (longitude) float64 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
    valid_time     (time, step) datetime64[ns] ...
  * isobaricInhPa  (isobaricInhPa) float64 1e+03 925.0 850.0 ... 100.0 50.0

In [4]:
tnc.info()

xarray.Dataset {
dimensions:
	number = 1 ;
	time = 1 ;
	step = 1 ;
	surface = 1 ;
	latitude = 721 ;
	longitude = 1440 ;
	isobaricInhPa = 13 ;

variables:
	int64 number(number) ;
		number:long_name = ensemble member numerical id ;
		number:units = 1 ;
		number:standard_name = realization ;
	datetime64[ns] time(time) ;
		time:long_name = initial time of forecast ;
		time:standard_name = forecast_reference_time ;
	timedelta64[ns] step(step) ;
		step:long_name = time since forecast_reference_time ;
		step:standard_name = forecast_period ;
	float64 surface(surface) ;
		surface:long_name = original GRIB coordinate for key: level(surface) ;
		surface:units = 1 ;
	float64 latitude(latitude) ;
		latitude:units = degrees_north ;
		latitude:standard_name = latitude ;
		latitude:long_name = latitude ;
		latitude:stored_direction = decreasing ;
	float64 longitude(longitude) ;
		longitude:units = degrees_east ;
		longitude:standard_name = longitude ;
		longitude:long_name = longitude ;
	datetime64[n

In [8]:
tnc["u10"].values = np.zeros((73,721,1440))

ValueError: replacement data must match the Variable's shape. replacement data has shape (73, 721, 1440); Variable has shape (1, 1, 1, 1, 721, 1440)

In [13]:
len(tnc["u10"].values.shape)

6

In [22]:
tnc["u10"].values.shape


(1, 1, 1, 1, 721, 1440)

In [19]:
tuple(range(4))

(0, 1, 2, 3)

In [21]:
len(tnc["u10"].shape) - 2

4

In [14]:
tnc["u"].values.shape

(1, 1, 1, 13, 721, 1440)

In [12]:
tnc["u10"].coords

Coordinates:
  * number      (number) int64 0
  * time        (time) datetime64[ns] 2021-01-01
  * step        (step) timedelta64[ns] 00:00:00
  * surface     (surface) float64 0.0
  * latitude    (latitude) float64 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * longitude   (longitude) float64 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
    valid_time  (time, step) datetime64[ns] ...

In [5]:
level=850

In [8]:
tnc["u"].sel(isobaricInhPa=level).values = np.zeros((1,1,1,721,1440))

In [10]:
output = np.zeros((73,721,1440))

In [11]:
tnc = output

In [12]:
tnc

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [10]:
tnc["u"].sel(isobaricInhPa=850).shape

(1, 1, 1, 721, 1440)

In [11]:
tnc["u"].shape

(1, 1, 1, 13, 721, 1440)

In [15]:
for var in tnc:
    print(var)

u10
v10
t2m
sp
msl
tcwv
u100
v100
t
u
v
z
r


In [25]:
template[8].field_metadata()

{'north': 90.0,
 'south': -90.0,
 'west': 0.0,
 'east': 359.75,
 'south_north_increment': 0.25,
 'west_east_increment': 0.25,
 'shortName': 't',
 'units': 'K',
 'paramId': '130',
 'level': '1000',
 'typeOfLevel': 'isobaricInhPa',
 'marsClass': 'ea',
 'marsStream': 'oper',
 'marsType': 'an',
 'number': '0',
 'stepRange': '0',
 'param': '130.128',
 'levelist': '1000',
 'shape': (721, 1440)}

In [2]:
dir = "/mnt/ssd2/Master/S2S_on_SFNO/outputs/sfno/leadtime_120_startDate_202101010_createdOn_20240115T0027/"

In [3]:
d = xr.open_dataset(dir+"leadtime_120_startDate_202101010_createdOn_20240115T0027_step_12.nc")

In [5]:
data = xr.open_mfdataset(dir+"*")

In [6]:
data.info()

xarray.Dataset {
dimensions:
	number = 1 ;
	time = 1 ;
	step = 20 ;
	surface = 1 ;
	latitude = 721 ;
	longitude = 1440 ;
	isobaricInhPa = 13 ;

variables:
	float32 u10(number, time, step, surface, latitude, longitude) ;
		u10:GRIB_paramId = 165 ;
		u10:GRIB_dataType = an ;
		u10:GRIB_numberOfPoints = 1038240 ;
		u10:GRIB_typeOfLevel = surface ;
		u10:GRIB_stepUnits = 1 ;
		u10:GRIB_stepType = instant ;
		u10:GRIB_gridType = regular_ll ;
		u10:GRIB_NV = 0 ;
		u10:GRIB_Nx = 1440 ;
		u10:GRIB_Ny = 721 ;
		u10:GRIB_cfName = unknown ;
		u10:GRIB_cfVarName = u10 ;
		u10:GRIB_gridDefinitionDescription = Latitude/Longitude Grid ;
		u10:GRIB_iDirectionIncrementInDegrees = 0.25 ;
		u10:GRIB_iScansNegatively = 0 ;
		u10:GRIB_jDirectionIncrementInDegrees = 0.25 ;
		u10:GRIB_jPointsAreConsecutive = 0 ;
		u10:GRIB_jScansPositively = 0 ;
		u10:GRIB_latitudeOfFirstGridPointInDegrees = 90.0 ;
		u10:GRIB_latitudeOfLastGridPointInDegrees = -90.0 ;
		u10:GRIB_longitudeOfFirstGridPointInDegrees = 0.0 ;
		u

In [4]:
dirg = "/mnt/ssd2/Master/S2S_on_SFNO/outputs/sfno/"

gdata = xr.open_dataset(dirg+"leadtime_120_startDate_202101010_createdOn_20240115T0006.grib")

skipping variable: paramId==228246 shortName='u100'
Traceback (most recent call last):
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 680, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 611, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=10.0) new_value=Variable(dimensions=(), data=100.0)
skipping variable: paramId==228247 shortName='v100'
Traceback (most recent call last):
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 680, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 611, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.Data

In [34]:
gdata2 = xr.open_dataset(dirg+"leadtime_120_startDate_202101010_createdOn_now.grib")

skipping variable: paramId==228246 shortName='u100'
Traceback (most recent call last):
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 680, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 611, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=10.0) new_value=Variable(dimensions=(), data=100.0)
skipping variable: paramId==228247 shortName='v100'
Traceback (most recent call last):
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 680, in build_dataset_components
    dict_merge(variables, coord_vars)
  File "/home/lenny/miniconda3/envs/model/lib/python3.11/site-packages/cfgrib/dataset.py", line 611, in dict_merge
    raise DatasetBuildError(
cfgrib.dataset.Data

In [9]:
du10 = data["u10"].to_numpy()

In [16]:
du10 = du10.squeeze()
du10.shape

(20, 721, 1440)

In [12]:
gu10 = gdata["u10"].to_numpy()

In [14]:
gu10.shape

(20, 721, 1440)

In [17]:
np.array_equal(du10,gu10)

False

In [18]:
du10

array([[[-1.083533  , -1.083533  , -1.083533  , ..., -1.083533  ,
         -1.083533  , -1.083533  ],
        [-4.902228  , -4.8904505 , -4.868965  , ..., -4.9458427 ,
         -4.9245863 , -4.926977  ],
        [-5.6167903 , -5.5893126 , -5.5540485 , ..., -5.6807246 ,
         -5.667745  , -5.6355624 ],
        ...,
        [-1.820684  , -1.816051  , -1.8190523 , ..., -1.8146545 ,
         -1.8144335 , -1.8214394 ],
        [-1.1536719 , -1.1472374 , -1.1498419 , ..., -1.1511095 ,
         -1.1517631 , -1.1554921 ],
        [ 1.9931746 ,  1.9931746 ,  1.9931746 , ...,  1.9931746 ,
          1.9931746 ,  1.9931746 ]],

       [[-1.0643024 , -1.0643024 , -1.0643024 , ..., -1.0643024 ,
         -1.0643024 , -1.0643024 ],
        [-4.4359026 , -4.4195523 , -4.4090667 , ..., -4.5048075 ,
         -4.47919   , -4.4613767 ],
        [-6.047192  , -6.0130844 , -5.9835596 , ..., -6.1080594 ,
         -6.082215  , -6.049476  ],
        ...,
        [ 0.92769134,  0.92735803,  0.9325366 , ...,  

In [19]:
gu10

array([[[-1.0788116 , -1.0788116 , -1.0788116 , ..., -1.0788116 ,
         -1.0788116 , -1.0788116 ],
        [-4.9049835 , -4.890335  , -4.886429  , ..., -4.945999  ,
         -4.919632  , -4.924515  ],
        [-5.6168976 , -5.5944366 , -5.555374  , ..., -5.664749  ,
         -5.6657257 , -5.645218  ],
        ...,
        [-1.8209991 , -1.8180695 , -1.8122101 , ..., -1.8151398 ,
         -1.8200226 , -1.8209991 ],
        [-1.1501007 , -1.1510773 , -1.1520538 , ..., -1.154007  ,
         -1.1501007 , -1.1481476 ],
        [ 1.9954071 ,  1.9954071 ,  1.9954071 , ...,  1.9954071 ,
          1.9954071 ,  1.9954071 ]],

       [[-1.0440674 , -1.0440674 , -1.0440674 , ..., -1.0440674 ,
         -1.0440674 , -1.0440674 ],
        [-4.437622  , -4.415161  , -4.404419  , ..., -4.5108643 ,
         -4.475708  , -4.4639893 ],
        [-6.045044  , -6.0264893 , -5.984497  , ..., -6.100708  ,
         -6.0821533 , -6.0684814 ],
        ...,
        [ 0.9256592 ,  0.93444824,  0.93933105, ...,  

In [23]:
gdata["u10"].sel(step=[np.timedelta64(2*60*60*10**9, 'ns')]).to_numpy()

KeyError: "not all values found in index 'step'"

In [37]:
gdata["u10"].sel(step='6:0:0').to_numpy()

array([[-1.0788116, -1.0788116, -1.0788116, ..., -1.0788116, -1.0788116,
        -1.0788116],
       [-4.9049835, -4.890335 , -4.886429 , ..., -4.945999 , -4.919632 ,
        -4.924515 ],
       [-5.6168976, -5.5944366, -5.555374 , ..., -5.664749 , -5.6657257,
        -5.645218 ],
       ...,
       [-1.8209991, -1.8180695, -1.8122101, ..., -1.8151398, -1.8200226,
        -1.8209991],
       [-1.1501007, -1.1510773, -1.1520538, ..., -1.154007 , -1.1501007,
        -1.1481476],
       [ 1.9954071,  1.9954071,  1.9954071, ...,  1.9954071,  1.9954071,
         1.9954071]], dtype=float32)

In [36]:
gdata2["u10"].sel(step='6:0:0').to_numpy()

array([[-1.0837784, -1.0837784, -1.0837784, ..., -1.0837784, -1.0837784,
        -1.0837784],
       [-4.9021378, -4.890419 , -4.8689346, ..., -4.946083 , -4.9245987,
        -4.926552 ],
       [-5.6169815, -5.5896378, -5.5544815, ..., -5.680458 , -5.6677628,
        -5.635536 ],
       ...,
       [-1.8210831, -1.8162003, -1.81913  , ..., -1.8142471, -1.8142471,
        -1.8210831],
       [-1.1540909, -1.147255 , -1.1501846, ..., -1.1511612, -1.1521378,
        -1.1550674],
       [ 1.99337  ,  1.99337  ,  1.99337  , ...,  1.99337  ,  1.99337  ,
         1.99337  ]], dtype=float32)

In [33]:
data["u10"].sel(step="6:0:0").to_numpy()

array([[[[[-1.083533 , -1.083533 , -1.083533 , ..., -1.083533 ,
           -1.083533 , -1.083533 ],
          [-4.902228 , -4.8904505, -4.868965 , ..., -4.9458427,
           -4.9245863, -4.926977 ],
          [-5.6167903, -5.5893126, -5.5540485, ..., -5.6807246,
           -5.667745 , -5.6355624],
          ...,
          [-1.820684 , -1.816051 , -1.8190523, ..., -1.8146545,
           -1.8144335, -1.8214394],
          [-1.1536719, -1.1472374, -1.1498419, ..., -1.1511095,
           -1.1517631, -1.1554921],
          [ 1.9931746,  1.9931746,  1.9931746, ...,  1.9931746,
            1.9931746,  1.9931746]]]]], dtype=float32)

In [39]:
np.array_equal(gu10.round(2),du10.round(2))

False

In [41]:
mask = gu10.round(2) == du10.round(2)


In [46]:
mask

array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True, False, ...,  True,  True, False],
        [ True,  True, False, ..., False,  True, False],
        ...,
        [ True,  True, False, ..., False, False,  True],
        [ True,  True,  True, ...,  True,  True, False],
        [False, False, False, ..., False, False, False]],

       [[False, False, False, ..., False, False, False],
        [ True,  True, False, ..., False,  True,  True],
        [ True, False,  True, ..., False,  True, False],
        ...,
        [ True,  True, False, ..., False, False,  True],
        [ True, False, False, ..., False,  True, False],
        [False, False, False, ..., False, False, False]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True, False,  True, ...,  True, False, False],
        [False,  True,  True, ..., False, False, False],
        ...,
        [ True, False, False, ...,  True,  True,  True],
        [False, False,  True, ..., False,  Tr

In [48]:
gu10[np.invert(mask)]

array([-4.886429 , -4.8336945, -4.789749 , ...,  4.180626 ,  4.180626 ,
        4.180626 ], dtype=float32)

In [49]:
du10[np.invert(mask)]

array([-4.868965 , -4.8415394, -4.7999682, ...,  4.1634617,  4.1634617,
        4.1634617], dtype=float32)

In [45]:
du10.round(2)

array([[[-1.08, -1.08, -1.08, ..., -1.08, -1.08, -1.08],
        [-4.9 , -4.89, -4.87, ..., -4.95, -4.92, -4.93],
        [-5.62, -5.59, -5.55, ..., -5.68, -5.67, -5.64],
        ...,
        [-1.82, -1.82, -1.82, ..., -1.81, -1.81, -1.82],
        [-1.15, -1.15, -1.15, ..., -1.15, -1.15, -1.16],
        [ 1.99,  1.99,  1.99, ...,  1.99,  1.99,  1.99]],

       [[-1.06, -1.06, -1.06, ..., -1.06, -1.06, -1.06],
        [-4.44, -4.42, -4.41, ..., -4.5 , -4.48, -4.46],
        [-6.05, -6.01, -5.98, ..., -6.11, -6.08, -6.05],
        ...,
        [ 0.93,  0.93,  0.93, ...,  0.94,  0.94,  0.93],
        [ 2.21,  2.22,  2.21, ...,  2.2 ,  2.21,  2.21],
        [ 4.9 ,  4.9 ,  4.9 , ...,  4.9 ,  4.9 ,  4.9 ]],

       [[-1.05, -1.05, -1.05, ..., -1.05, -1.05, -1.05],
        [-4.47, -4.45, -4.44, ..., -4.52, -4.49, -4.48],
        [-6.53, -6.51, -6.5 , ..., -6.59, -6.56, -6.55],
        ...,
        [ 2.05,  2.05,  2.05, ...,  2.05,  2.05,  2.05],
        [ 3.58,  3.59,  3.58, ...,  3.58,  3.

In [50]:
data.to_netcdf(dirg+"combinded.nc")

In [51]:
20*300

6000