In [1]:
import xarray as xr
import numpy as np

# from torch.utils.data import BatchSampler, IterableDataset
from calendar import isleap
# import torch
import os
import cftime
from time import time

In [2]:
import glob

In [3]:

print("cuda available? : ",torch.cuda.is_available(),flush=True)

NameError: name 'torch' is not defined

In [4]:
path ="/mnt/ceph/goswamicd/datasets/weatherbench2/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr"
path_weird = "/mnt/ceph/goswamicd/datasets/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr"

In [5]:
path_2 ="/mnt/ceph/goswamicd/datasets/weatherbench2/era5/1959-2023_01_10-6h-240x121_equiangular_with_poles_conservative.zarr"

In [6]:
path_3= "/mnt/ceph/goswamicd/datasets/1990-2017_6h_1440x721.zarr"

In [7]:
path_uv = "/mnt/ceph/goswamicd/datasets/weatherbench2/era5/1959-2023_01_10-u100mv100m-6h-1440x721"

In [8]:
files = glob.glob("/mnt/qb/goswami/data/era5/single_pressure_level/100m_u_component_of_wind/100m_u_component_of_wind_????.nc")

In [9]:
files[:1]

['/mnt/qb/goswami/data/era5/single_pressure_level/100m_u_component_of_wind/100m_u_component_of_wind_1959.nc']

In [10]:
path_ceph_u = "/mnt/ceph/goswamicd/datasets/weatherbench2/era5/u100m_1959-2022_721x1440_correct_chunk.zarr"
path_ceph_v = "/mnt/ceph/goswamicd/datasets/weatherbench2/era5/v100m_1959-2023-10_721x1440_correct_chunk.zarr"

In [11]:
path_u = "/mnt/qb/goswami/data/era5/single_pressure_level/100m_u_component_of_wind/100m_u_component_of_wind_????.nc"
path_v = "/mnt/qb/goswami/data/era5/single_pressure_level/100m_v_component_of_wind/100m_v_component_of_wind_????.nc"

In [12]:
base_path ="/mnt/ceph/goswamicd/datasets"

In [13]:
wb2_base_path = "/mnt/qb/goswami/data/era5/weatherbench2"
wb2_path = "/mnt/qb/goswami/data/era5/weatherbench2/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr"
wb2_path2 = "/mnt/qb/goswami/data/era5/weatherbench2/1990-2019_6h_1440x721.zarr"
wb2_chunk_path = "/mnt/qb/goswami/data/era5/weatherbench2/1959-2022-wb13-6h-0p25deg-chunk-1.zarr-v2"

In [14]:
base_path_uv = "/mnt/qb/goswami/data/era5/u100m_v100m_721x1440"
u_rechunked = "u100m_chunked_1959-2022_721x1440_correct_chunk_new_mean_INTERPOLATE.zarr"
a="ttr_1959-2023-10_721x1440.zarr"
b="u100m_climatology_1990-2017_721x1440.zarr"

c="ttr_climatology_1990-2017_721x1440_smoothed.zarr"
d="v100m_1959-2023-10_721x1440_correct_chunk_new_mean_INTERPOLATE.zarr"

e="u100m_1959-2022_721x1440_correct_chunk_new_mean_INTERPOLATE.zarr"
f="v100m_climatology_1990-2017_721x1440_smoothed.zarr"

g="u100m_climatology_1990-2017_721x1440_smoothed.zarr"
h="v100m_climatology_1990-2017_721x1440.zarr"

In [26]:
uchunk = xr.open_zarr(os.path.join(base_path_uv,e))

In [39]:
u_rechunked_chunk = xr.open_zarr(os.path.join(wb2_base_path,u_rechunked))



/tmp/ipykernel_893160/1356717232.py:1: RuntimeWarning: Failed to open Zarr store with consolidated metadata, but successfully read with non-consolidated metadata. This is typically much slower for opening a dataset. To silence this warning, consider:
1. Consolidating metadata in this existing store with zarr.consolidate_metadata().
2. Explicitly setting consolidated=False, to avoid trying to read consolidate metadata, or
3. Explicitly setting consolidated=True, to raise an error in this case instead of falling back to try reading non-consolidated metadata.
  u_rechunked_chunk = xr.open_zarr(os.path.join(wb2_base_path,u_rechunked))


In [22]:
u_rechunked_chunk

<xarray.Dataset> Size: 388GB
Dimensions:    (latitude: 721, longitude: 1440, time: 93500)
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 748kB 1959-01-01 ... 2022-12-30T18:00:00
Data variables:
    u100       (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [27]:
uchunk

<xarray.Dataset> Size: 388GB
Dimensions:    (latitude: 721, longitude: 1440, time: 93500)
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 748kB 1959-01-01 ... 2022-12-30T18:00:00
Data variables:
    u100       (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [11]:
rechunk:
23.3

normal:
47.7

SyntaxError: invalid syntax (1042158755.py, line 1)

In [17]:
idx = np.arange(0,90000)
np.random.shuffle(idx)
step = 200

In [18]:

s = time()
for i in range(0,step):
    a = uchunk.isel(time=idx[i])
    a.to_array().to_numpy()
e = time()
print(e-s)

30.383786916732788


In [16]:

s = time()
for i in range(0,step):
    a = u_rechunked_chunk.isel(time=idx[i])
    a.to_array().to_numpy()
e = time()
print(e-s)

15.569042205810547


In [40]:
i=300
t1 = u_rechunked_chunk.isel(time=i).to_array().to_numpy()
t2 = uchunk.isel(time=i).to_array().to_numpy()

# np.equal(t1,t2)

In [41]:
t1

array([[[ -0.06480768, -39.233013  ,  55.923107  , ...,   0.35875383,
           0.35875383,   0.35875383],
        [ -2.0546825 ,  -2.077157  ,  -2.097903  , ...,  -1.9855294 ,
          -2.0080042 ,  -2.0322077 ],
        [ -1.8956306 ,  -1.9250207 ,  -1.9613259 , ...,  -1.7815284 ,
          -1.8264778 ,  -1.8662406 ],
        ...,
        [ -5.749176  ,  -5.7249727 ,  -5.6869383 , ...,  -5.8338885 ,
          -5.799312  ,  -5.769922  ],
        [ -4.5925937 ,  -4.5683904 ,  -4.5441866 , ...,  -4.649645  ,
          -4.630628  ,  -4.611611  ],
        [  1.0831305 ,   1.0831305 ,   1.0831305 , ...,   1.0831305 ,
           1.0831305 ,   1.0831305 ]]], dtype=float32)

In [35]:
t2

array([[[-0.19792701, -0.19792701, -0.19792701, ..., -0.19792701,
         -0.19792701, -0.19792701],
        [ 0.07868457,  0.05620989,  0.03719285, ...,  0.13919336,
          0.11844751,  0.09943044],
        [ 0.4711273 ,  0.44519493,  0.4106185 , ...,  0.57312787,
          0.5316361 ,  0.49878845],
        ...,
        [ 1.067571  ,  1.0986899 ,  1.1401817 , ...,  0.9551976 ,
          1.0018758 ,  1.0416387 ],
        [ 0.74601007,  0.7719424 ,  0.7978748 , ...,  0.67339957,
          0.697603  ,  0.72007775],
        [ 0.36048266,  0.36048266,  0.36048266, ...,  0.36048266,
          0.36048266,  0.36048266]]], dtype=float32)

In [37]:
t1

array([[[-6.4807683e-02, -3.9233013e+01,  5.5923107e+01, ...,
         -1.9792701e-01, -1.9792701e-01, -1.9792701e-01],
        [ 7.8684568e-02,  5.6209892e-02,  3.7192851e-02, ...,
          1.3919336e-01,  1.1844751e-01,  9.9430442e-02],
        [ 4.7112730e-01,  4.4519493e-01,  4.1061851e-01, ...,
          5.7312787e-01,  5.3163612e-01,  4.9878845e-01],
        ...,
        [ 1.0675710e+00,  1.0986899e+00,  1.1401817e+00, ...,
          9.5519757e-01,  1.0018758e+00,  1.0416387e+00],
        [ 7.4601007e-01,  7.7194238e-01,  7.9787481e-01, ...,
          6.7339957e-01,  6.9760299e-01,  7.2007775e-01],
        [ 3.6048266e-01,  3.6048266e-01,  3.6048266e-01, ...,
          3.6048266e-01,  3.6048266e-01,  3.6048266e-01]]], dtype=float32)

In [38]:
t2

array([[[ 0.35875383,  0.35875383,  0.35875383, ...,  0.35875383,
          0.35875383,  0.35875383],
        [-2.0546825 , -2.077157  , -2.097903  , ..., -1.9855294 ,
         -2.0080042 , -2.0322077 ],
        [-1.8956306 , -1.9250207 , -1.9613259 , ..., -1.7815284 ,
         -1.8264778 , -1.8662406 ],
        ...,
        [-5.749176  , -5.7249727 , -5.6869383 , ..., -5.8338885 ,
         -5.799312  , -5.769922  ],
        [-4.5925937 , -4.5683904 , -4.5441866 , ..., -4.649645  ,
         -4.630628  , -4.611611  ],
        [ 1.0831305 ,  1.0831305 ,  1.0831305 , ...,  1.0831305 ,
          1.0831305 ,  1.0831305 ]]], dtype=float32)

In [24]:
idx = np.arange(0,90000)
np.random.shuffle(idx)

step = 120

s = time()
for i in range(0,step):
    a = u_rechunked_chunk.isel(time=idx[i])
    a.to_array().to_numpy()
e = time()
print(e-s)

s = time()
for i in range(step,step+step):
    a = u_rechunked_chunk.isel(time=idx[i])
    a.to_array().to_numpy()
e = time()
print(e-s)

    

1.2729380130767822
1.2838115692138672


In [7]:
a = uchunk.sel(time=slice("1.1.2020","1.5.2020"))

In [9]:
a

<xarray.Dataset> Size: 83MB
Dimensions:    (latitude: 721, longitude: 1440, time: 20)
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 160B 2020-01-01 ... 2020-01-05T18:00:00
Data variables:
    u100       (time, latitude, longitude) float32 83MB ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [10]:
save_path = "/mnt/qb/goswami/data/era5/weatherbench2"
a.to_zarr(os.path.join(save_path,"u100_smallset_test.zarr"))

In [12]:
sm = xr.open_dataset(os.path.join(save_path,"u100_smallset_test.zarr"))

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


In [15]:
sm.chunk

<bound method Dataset.chunk of <xarray.Dataset> Size: 83MB
Dimensions:    (latitude: 721, longitude: 1440, time: 20)
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 160B 2020-01-01 ... 2020-01-05T18:00:00
Data variables:
    u100       (time, latitude, longitude) float32 83MB ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...>

In [14]:
uchunk.info.chunk

AttributeError: 'function' object has no attribute 'chunk'

In [45]:
data = xr.open_zarr(wb2_path)

In [46]:
data

<xarray.Dataset> Size: 89TB
Dimensions:                                           (time: 93544,
                                                       latitude: 721,
                                                       longitude: 1440,
                                                       level: 13)
Coordinates:
  * latitude                                          (latitude) float32 3kB ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float32 6kB ...
  * time                                              (time) datetime64[ns] 748kB ...
Data variables: (12/62)
    10m_u_component_of_wind                           (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    10m_v_component_of_wind                           (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    10m_wind_speed                                    (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    2m_dewpoint_temperature                           (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    2m_temperature                                    (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    above_ground                                      (time, level, latitude, longitude) float32 5TB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    ...                                                ...
    volumetric_soil_water_layer_1                     (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    volumetric_soil_water_layer_2                     (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    volumetric_soil_water_layer_3                     (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    volumetric_soil_water_layer_4                     (time, latitude, longitude) float32 388GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    vorticity                                         (time, level, latitude, longitude) float32 5TB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    wind_speed                                        (time, level, latitude, longitude) float32 5TB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>

In [48]:
uera5 = xr.open_mfdataset(path_u)
# uera5.chunk
#uera5["u100"].chunk # takes for eeever

<bound method Dataset.chunk of <xarray.Dataset> Size: 2TB
Dimensions:    (longitude: 1440, latitude: 721, time: 569784)
Coordinates:
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 5MB 1959-01-01 ... 2023-12-31T23:00:00
Data variables:
    u100       (time, latitude, longitude) float32 2TB dask.array<chunksize=(8760, 721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...>

In [37]:
# compare era5 with zarr
uera5_a = uera5.isel(time=1001*6)["u100"]
uchunk_a = uchunk.isel(time=1001)["u100"]
print(uera5_a.mean().to_numpy())
print("----")
print(uchunk_a.mean().to_numpy())

-0.09254253
----
-0.09254253


In [22]:
uera5_a

<xarray.DataArray 'u100' (latitude: 721, longitude: 1440)> Size: 4MB
dask.array<getitem, shape=(721, 1440), dtype=float32, chunksize=(721, 1440), chunktype=numpy.ndarray>
Coordinates:
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
    time       datetime64[ns] 8B 1959-01-05T04:00:00
Attributes:
    units:      m s**-1
    long_name:  100 metre U wind component

In [23]:
uchunk_a

<xarray.DataArray 'u100' (latitude: 721, longitude: 1440)> Size: 4MB
[1038240 values with dtype=float32]
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
    time       datetime64[ns] 8B 1959-01-26
Attributes:
    long_name:  100 metre U wind component
    units:      m s**-1

In [30]:
uera5.isel(time=11)["u100"].mean().to_numpy()

array(0.03568938, dtype=float32)

In [36]:
uchunk.sel(time="1959-03-11T00:00:00").isel(longitude=100,latitude=100).to_array()

<xarray.DataArray (variable: 1)> Size: 4B
array([6.599803], dtype=float32)
Coordinates:
    latitude   float32 4B 65.0
    longitude  float32 4B 25.0
    time       datetime64[ns] 8B 1959-03-11
  * variable   (variable) object 8B 'u100'
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [23]:
x = xr.open_dataset("/mnt/qb/goswami/data/era5/single_pressure_level/100m_u_component_of_wind/100m_u_component_of_wind_1959.nc")

In [35]:
x.sel(time="1959-03-11T00:00:00").isel(longitude=100,latitude=100).to_array()

<xarray.DataArray (variable: 1)> Size: 4B
array([6.599803], dtype=float32)
Coordinates:
    longitude  float32 4B 25.0
    latitude   float32 4B 65.0
    time       datetime64[ns] 8B 1959-03-11
  * variable   (variable) object 8B 'u100'
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [29]:
x.chunks

Frozen({})

In [19]:
t1 = uera5.isel(time=1000)
t1

<xarray.Dataset> Size: 4MB
Dimensions:    (longitude: 1440, latitude: 721)
Coordinates:
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
    time       datetime64[ns] 8B 1959-02-11T16:00:00
Data variables:
    u100       (latitude, longitude) float32 4MB dask.array<chunksize=(721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [20]:
t1.isel(longitude=100,latitude=100).to_array()

<xarray.DataArray (variable: 1)> Size: 4B
dask.array<stack, shape=(1,), dtype=float32, chunksize=(1,), chunktype=numpy.ndarray>
Coordinates:
    longitude  float32 4B 25.0
    latitude   float32 4B 65.0
    time       datetime64[ns] 8B 1959-02-11T16:00:00
  * variable   (variable) object 8B 'u100'
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [21]:
t2.isel(longitude=100,latitude=100).to_array()

<xarray.DataArray (variable: 1)> Size: 4B
array([2.4402559], dtype=float32)
Coordinates:
    latitude   float32 4B 65.0
    longitude  float32 4B 25.0
    time       datetime64[ns] 8B 1959-09-08
  * variable   (variable) object 8B 'u100'
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [ ]:
t1n = t1.to_array().to_numpy()
t2n = t2.to_array().to_numpy()

In [ ]:
t1.to_array().mean().to_numpy()

In [ ]:
t2.to_array().mean.to_numpy()

In [11]:
vchunk = xr.open_dataset(os.path.join(base_path_uv,d))

NameError: name 'base_path_uv' is not defined

In [10]:
vchunk.chunk


NameError: name 'vchunk' is not defined

In [13]:
wb2 = xr.open_dataset(wb2_path)
wb2["10m_u_component_of_wind"].chunk

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


<bound method DataArray.chunk of <xarray.DataArray '10m_u_component_of_wind' (time: 93544, latitude: 721,
                                             longitude: 1440)> Size: 388GB
[97121122560 values with dtype=float32]
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 748kB 1959-01-01 ... 2023-01-10T18:00:00
Attributes:
    long_name:   10 metre U wind component
    short_name:  u10
    units:       m s**-1>

In [15]:
wb2_chunk = xr.open_zarr(wb2_chunk_path)
wb2_chunk["10m_u_component_of_wind"].chunk

RuntimeError: error during blosc decompression: 0

In [35]:
wb2_chunk.chunk

<bound method Dataset.chunk of <xarray.Dataset> Size: 36TB
Dimensions:                                           (time: 92044,
                                                       latitude: 721,
                                                       longitude: 1440,
                                                       level: 13)
Coordinates:
  * latitude                                          (latitude) float32 3kB ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float32 6kB ...
  * time                                              (time) datetime64[ns] 736kB ...
Data variables: (12/36)
    10m_u_component_of_wind                           (time, latitude, longitude) float32 382GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    10m_v_component_of_wind                           (time, latitude, longitude) float32 382GB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray

In [33]:
print(wb2_chunk.isel(time=1001*6)["10m_u_component_of_wind"])

<xarray.DataArray '10m_u_component_of_wind' (latitude: 721, longitude: 1440)> Size: 4MB
dask.array<getitem, shape=(721, 1440), dtype=float32, chunksize=(721, 1440), chunktype=numpy.ndarray>
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
    time       datetime64[ns] 8B 1963-02-10T12:00:00
Attributes:
    long_name:   10 metre U wind component
    short_name:  u10
    units:       m s**-1


In [4]:
wb2_2 = xr.open_dataset(wb2_path2)
wb2_2

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


<xarray.Dataset> Size: 1TB
Dimensions:                                         (hour: 4, dayofyear: 366,
                                                     latitude: 721,
                                                     longitude: 1440, level: 13)
Coordinates:
  * dayofyear                                       (dayofyear) int64 3kB 1 ....
  * hour                                            (hour) int64 32B 0 6 12 18
  * latitude                                        (latitude) float32 3kB 90...
  * level                                           (level) int64 104B 50 ......
  * longitude                                       (longitude) float32 6kB 0...
Data variables: (12/53)
    10m_u_component_of_wind                         (hour, dayofyear, latitude, longitude) float32 6GB ...
    10m_v_component_of_wind                         (hour, dayofyear, latitude, longitude) float32 6GB ...
    10m_wind_speed                                  (hour, dayofyear, latitude, longitude) float32 6GB ...
    2m_dewpoint_temperature                         (hour, dayofyear, latitude, longitude) float32 6GB ...
    2m_temperature                                  (hour, dayofyear, latitude, longitude) float32 6GB ...
    above_ground                                    (hour, dayofyear, level, latitude, longitude) float32 79GB ...
    ...                                              ...
    volumetric_soil_water_layer_1                   (hour, dayofyear, latitude, longitude) float32 6GB ...
    volumetric_soil_water_layer_2                   (hour, dayofyear, latitude, longitude) float32 6GB ...
    volumetric_soil_water_layer_3                   (hour, dayofyear, latitude, longitude) float32 6GB ...
    volumetric_soil_water_layer_4                   (hour, dayofyear, latitude, longitude) float32 6GB ...
    vorticity                                       (hour, dayofyear, level, latitude, longitude) float32 79GB ...
    wind_speed                                      (hour, dayofyear, level, latitude, longitude) float32 79GB ...

In [24]:
# check chunky load time
s = time()
for i in range(20):
    idx = np.random.randint(0,90000)
    data = wb2_chunk.isel(time=idx)[["geopotential","v_component_of_wind","temperature"]].sel(level=[1000,925,850,700,600,500,400,300,250,200,150,100,50]).to_array().to_numpy()
e = time()
print(e-s)

19.63910484313965


In [25]:
# check chunky load time
s = time()
for i in range(20):
    idx = np.random.randint(0,90000)
    data = wb2.isel(time=idx)[["geopotential","v_component_of_wind","temperature"]].sel(level=[1000,925,850,700,600,500,400,300,250,200,150,100,50]).to_array().to_numpy()
e = time()
print(e-s)

33.26441717147827


In [5]:
dsw = xr.open_dataset(path_weird)

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


In [7]:
d = dsw.isel(time=0)

In [9]:
dn = d.to_numpy()

In [10]:
dn

array([[-0.03886533, -0.03886533, -0.03886533, ..., -0.03886533,
        -0.03886533, -0.03886533],
       [-2.8309908 , -2.8350334 , -2.839076  , ..., -2.815494  ,
        -2.8202105 , -2.8262744 ],
       [-2.896347  , -2.9003897 , -2.9064536 , ..., -2.8707435 ,
        -2.8808503 , -2.8896093 ],
       ...,
       [-4.476351  , -4.487131  , -4.5006065 , ..., -4.4231224 ,
        -4.4440093 , -4.462875  ],
       [-4.5417066 , -4.5497923 , -4.5578775 , ..., -4.508692  ,
        -4.520146  , -4.530926  ],
       [ 0.33508003,  0.33508003,  0.33508003, ...,  0.33508003,
         0.33508003,  0.33508003]], dtype=float32)

In [2]:
from S2S_on_SFNO.Models.train import train

In [6]:
train({"training_workers":0,"batch_size":1})

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


Training on years:
     2000  -  2010


PermissionError: [Errno 13] Permission denied: '/mnt/ceph/goswamicd/datasets/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr/10m_v_component_of_wind/62004.0.0'

In [4]:
ds = xr.open_dataset(path,engine='zarr')

FileNotFoundError: No such file or directory: '/mnt/ceph/goswamicd/datasets/weatherbench2/era5/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr'

In [8]:
xr.open_dataset("/mnt/ceph/goswamicd/datasets/1959-2023_01_10-wb13-6h-1440x721_with_derived_variables.zarr/10m_v_component_of_wind/62004.0.0")

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:168: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:168: RuntimeWarning: 'h5netcdf' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:168: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'scipy', 'cfgrib', 'zarr']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html

In [3]:
uv = xr.open_dataset(path_)

PermissionError: [Errno 13] Permission denied: '/mnt/ceph/goswamicd/datasets/weatherbench2/era5/1959-2023_01_10-u100mv100m-6h-1440x721'

In [8]:
uv = xr.open_dataset(path)

/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'netcdf4' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)
/opt/conda/envs/model/lib/python3.11/site-packages/xarray/backends/plugins.py:159: RuntimeWarning: 'scipy' fails while guessing
  warnings.warn(f"{engine!r} fails while guessing", RuntimeWarning)


In [24]:
v_ceph =  xr.open_dataset(path_ceph_v,engine='zarr')

In [28]:
v_ceph

<xarray.Dataset> Size: 388GB
Dimensions:    (latitude: 721, longitude: 1440, time: 93544)
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 748kB 1959-01-01 ... 2023-01-10T18:00:00
Data variables:
    v100       (time, latitude, longitude) float32 388GB ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:35:34 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [27]:
u_ceph =  xr.open_dataset(path_ceph_u,engine='zarr')
u_ceph.info

<bound method Dataset.info of <xarray.Dataset> Size: 388GB
Dimensions:    (latitude: 721, longitude: 1440, time: 93505)
Coordinates:
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * time       (time) datetime64[ns] 748kB 1959-01-01 ... 2023-01-01
Data variables:
    u100       (time, latitude, longitude) float32 388GB ...
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...>

In [8]:
v_o = xr.open_mfdataset(path_v)

In [26]:
v_o.sel(expver=1)

<xarray.Dataset> Size: 2TB
Dimensions:    (longitude: 1440, latitude: 721, time: 569784)
Coordinates:
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 5MB 1959-01-01 ... 2023-12-31T23:00:00
    expver     int32 4B 1
Data variables:
    v100       (time, latitude, longitude) float32 2TB dask.array<chunksize=(8760, 721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:35:34 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...

In [25]:
if "expver" in set(v_o.coords.dims): print("true")

true


In [ ]:
dict(se

In [23]:
u_o = xr.open_mfdataset(path_u)
u_o.info

<bound method Dataset.info of <xarray.Dataset> Size: 2TB
Dimensions:    (longitude: 1440, latitude: 721, time: 561024)
Coordinates:
  * longitude  (longitude) float32 6kB 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
  * latitude   (latitude) float32 3kB 90.0 89.75 89.5 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 4MB 1959-01-01 ... 2022-12-31T23:00:00
Data variables:
    u100       (time, latitude, longitude) float32 2TB dask.array<chunksize=(8760, 721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2024-02-16 17:16:09 GMT by grib_to_netcdf-2.25.1: /opt/ecmw...>

In [7]:
for k in ds.keys():
    print(k)

10m_u_component_of_wind
10m_v_component_of_wind
10m_wind_speed
2m_dewpoint_temperature
2m_temperature
above_ground
ageostrophic_wind_speed
angle_of_sub_gridscale_orography
anisotropy_of_sub_gridscale_orography
boundary_layer_height
divergence
eddy_kinetic_energy
geopotential
geopotential_at_surface
geostrophic_wind_speed
high_vegetation_cover
integrated_vapor_transport
lake_cover
land_sea_mask
lapse_rate
leaf_area_index_high_vegetation
leaf_area_index_low_vegetation
low_vegetation_cover
mean_sea_level_pressure
mean_surface_latent_heat_flux
mean_surface_net_long_wave_radiation_flux
mean_surface_net_short_wave_radiation_flux
mean_surface_sensible_heat_flux
mean_top_downward_short_wave_radiation_flux
mean_top_net_long_wave_radiation_flux
mean_top_net_short_wave_radiation_flux
mean_vertically_integrated_moisture_divergence
potential_vorticity
relative_humidity
sea_ice_cover
sea_surface_temperature
slope_of_sub_gridscale_orography
snow_depth
soil_type
specific_humidity
standard_deviation_of

In [14]:
ds2 = xr.open_dataset(path_2,engine='zarr')

In [15]:
ds2.info

<bound method Dataset.info of <xarray.Dataset>
Dimensions:                                           (time: 93544,
                                                       longitude: 240,
                                                       latitude: 121, level: 13)
Coordinates:
  * latitude                                          (latitude) float64 -90....
  * level                                             (level) int64 50 ... 1000
  * longitude                                         (longitude) float64 0.0...
  * time                                              (time) datetime64[ns] 1...
Data variables: (12/62)
    10m_u_component_of_wind                           (time, longitude, latitude) float32 ...
    10m_v_component_of_wind                           (time, longitude, latitude) float32 ...
    10m_wind_speed                                    (time, longitude, latitude) float32 ...
    2m_dewpoint_temperature                           (time, longitude, latitude) float32 .

In [16]:
ds3 = xr.open_dataset(path_3,engine='zarr')

In [17]:
ds3.info

<bound method Dataset.info of <xarray.Dataset>
Dimensions:                                         (hour: 4, dayofyear: 366,
                                                     latitude: 721,
                                                     longitude: 1440, level: 13)
Coordinates:
  * dayofyear                                       (dayofyear) int64 1 ... 366
  * hour                                            (hour) int64 0 6 12 18
  * latitude                                        (latitude) float32 90.0 ....
  * level                                           (level) int64 50 ... 1000
  * longitude                                       (longitude) float32 0.0 ....
Data variables: (12/53)
    10m_u_component_of_wind                         (hour, dayofyear, latitude, longitude) float32 ...
    10m_v_component_of_wind                         (hour, dayofyear, latitude, longitude) float32 ...
    10m_wind_speed                                  (hour, dayofyear, latitude, longitud

In [ ]:
path_era5 = "/mnt/qb/goswami/data/era5/single_pressure_level/"

In [ ]:
era5_nc = os.path.join(path_era5+"100m_v_component_of_wind/100m_v_component_of_wind_????.nc")
era5_nc


In [11]:
m10 = xr.open_mfdataset(era5_nc)

In [17]:
ds["2m_temperature"]


<xarray.DataArray '2m_temperature' (time: 93544, latitude: 721, longitude: 1440)>
[97121122560 values with dtype=float32]
Coordinates:
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * time       (time) datetime64[ns] 1959-01-01 ... 2023-01-10T18:00:00
Attributes:
    long_name:   2 metre temperature
    short_name:  t2m
    units:       K

In [33]:
ms = ds[["mean_sea_level_pressure","surface_pressure"]]
ms.isel(time=0,latitude=0,longitude=0).to_array().to_numpy()

array([100667.266, 100666.87 ], dtype=float32)

In [32]:
ms2 = ds[["surface_pressure","mean_sea_level_pressure"]]
ms2.isel(time=0,latitude=0,longitude=0).to_array().to_numpy()

array([100666.87 , 100667.266], dtype=float32)

In [40]:
dst = ds[["temperature","geopotential","mean_sea_level_pressure"]]

In [41]:
dst

<xarray.Dataset>
Dimensions:                  (time: 93544, level: 13, latitude: 721,
                              longitude: 1440)
Coordinates:
  * latitude                 (latitude) float32 90.0 89.75 89.5 ... -89.75 -90.0
  * level                    (level) int64 50 100 150 200 ... 700 850 925 1000
  * longitude                (longitude) float32 0.0 0.25 0.5 ... 359.5 359.8
  * time                     (time) datetime64[ns] 1959-01-01 ... 2023-01-10T...
Data variables:
    temperature              (time, level, latitude, longitude) float32 ...
    geopotential             (time, level, latitude, longitude) float32 ...
    mean_sea_level_pressure  (time, latitude, longitude) float32 ...

In [44]:
dst_l = dst.sel(level=[50,200,300])
dst_l

<xarray.Dataset>
Dimensions:                  (time: 93544, level: 3, latitude: 721,
                              longitude: 1440)
Coordinates:
  * latitude                 (latitude) float32 90.0 89.75 89.5 ... -89.75 -90.0
  * level                    (level) int64 50 200 300
  * longitude                (longitude) float32 0.0 0.25 0.5 ... 359.5 359.8
  * time                     (time) datetime64[ns] 1959-01-01 ... 2023-01-10T...
Data variables:
    temperature              (time, level, latitude, longitude) float32 ...
    geopotential             (time, level, latitude, longitude) float32 ...
    mean_sea_level_pressure  (time, latitude, longitude) float32 ...

In [52]:
slic = dst_l.sel(latitude=slice(10,0),longitude=slice(0,10.))
slic = slic.isel(time=0)

In [53]:
slic

<xarray.Dataset>
Dimensions:                  (level: 3, latitude: 41, longitude: 41)
Coordinates:
  * latitude                 (latitude) float32 10.0 9.75 9.5 ... 0.5 0.25 0.0
  * level                    (level) int64 50 200 300
  * longitude                (longitude) float32 0.0 0.25 0.5 ... 9.5 9.75 10.0
    time                     datetime64[ns] 1959-01-01
Data variables:
    temperature              (level, latitude, longitude) float32 ...
    geopotential             (level, latitude, longitude) float32 ...
    mean_sea_level_pressure  (latitude, longitude) float32 ...

In [54]:
slic_n = slic.to_array().to_numpy()

In [65]:
tst = slic_n[:,:,0,0]
print(slic_n.shape)
tst

(3, 3, 41, 41)


array([[   204.66138,    219.3152 ,    241.60149],
       [201373.28   , 121580.195  ,  94754.5    ],
       [101104.07   , 101104.07   , 101104.07   ]], dtype=float32)

In [75]:
tup = list(slic_n.shape)
tup[0] = tup[0]*tup[1]
del tup[1]
tt = tuple(tup)

In [77]:
x = slic_n.reshape(tt)

In [89]:
levels_per_pl = {"u_component_of_wind":[1000,925,850,700,600,500,400,300,250,200,150,100,50],
                     "v_component_of_wind":[1000,925,850,700,600,500,400,300,250,200,150,100,50],
                     "geopotential":[1000,925,850,700,600,500,400,300,250,200,150,100,50],
                     "temperature":[1000,925,850,700,600,500,400,300,250,200,150,100,50],
                     "relative_humidity":[1000,925,850,700,600,500,400,300,250,200,150,100,50]}
param_sfc_ERA5 = ["10m_u_component_of_wind", "10m_v_component_of_wind", "2m_temperature", "surface_pressure", "mean_sea_level_pressure", "total_column_water_vapour"]

param_level_pl = (
    [ "u", "v", "z", "t", "r"],
    [1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50],
)

In [84]:
sample = ds.isel(time=0)

In [85]:
scf = sample[param_sfc_ERA5]

In [87]:
scf_n = scf.to_array().to_numpy()

In [140]:
scf_n.shape

(6, 721, 1440)

In [128]:
param_level_pl[1]

[1000, 925, 850, 700, 600, 500, 400, 300, 250, 200, 150, 100, 50]

In [124]:
testlist = param_level_pl[1].copy()

In [126]:
testlist.reverse()

In [127]:
testlist

[50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]

In [129]:

pl = sample[list(levels_per_pl.keys())].sel(level=testlist)

In [130]:
pl

<xarray.Dataset>
Dimensions:              (level: 13, latitude: 721, longitude: 1440)
Coordinates:
  * latitude             (latitude) float32 90.0 89.75 89.5 ... -89.75 -90.0
  * level                (level) int64 50 100 150 200 250 ... 700 850 925 1000
  * longitude            (longitude) float32 0.0 0.25 0.5 ... 359.2 359.5 359.8
    time                 datetime64[ns] 1959-01-01
Data variables:
    u_component_of_wind  (level, latitude, longitude) float32 ...
    v_component_of_wind  (level, latitude, longitude) float32 ...
    geopotential         (level, latitude, longitude) float32 ...
    temperature          (level, latitude, longitude) float32 ...
    relative_humidity    (level, latitude, longitude) float32 ...

In [131]:
scf = pl.to_array().to_numpy()

In [132]:
pl_r = pl_n.reshape((pl_n.shape[0]*pl_n.shape[1], pl_n.shape[2], pl_n.shape[3]))

In [133]:
pl_r.shape

(65, 721, 1440)

In [134]:
for i in range(0,5):
    print(pl_r[i,0,0])

0.0012388229
0.0003900528
-0.0004234314
-0.0001411438
0.0019130707


In [141]:
t = np.vstack((scf_n,pl_r))

In [142]:
t.shape

(71, 721, 1440)

In [146]:
a = scf_n[2:]

In [150]:
sa = scf_n[:2]
sa.shape

(2, 721, 1440)

In [156]:
scf_n[2,0,0]

240.76831

In [155]:
a[0,0,0]

240.76831

In [ ]:
sa[0,0,0]

In [25]:
ds.filter_by_attrs({short_name="2t",short_name="sp"})

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (1543698265.py, line 1)

In [11]:
ds.isel(time=93504)

<xarray.Dataset>
Dimensions:                                           (latitude: 721,
                                                       longitude: 1440,
                                                       level: 13)
Coordinates:
  * latitude                                          (latitude) float32 90.0...
  * level                                             (level) int64 50 ... 1000
  * longitude                                         (longitude) float32 0.0...
    time                                              datetime64[ns] 2023-01-01
Data variables: (12/62)
    10m_u_component_of_wind                           (latitude, longitude) float32 ...
    10m_v_component_of_wind                           (latitude, longitude) float32 ...
    10m_wind_speed                                    (latitude, longitude) float32 ...
    2m_dewpoint_temperature                           (latitude, longitude) float32 ...
    2m_temperature                                    (latitude, longitude) float32 ...
    above_ground                                      (level, latitude, longitude) float32 ...
    ...                                                ...
    volumetric_soil_water_layer_1                     (latitude, longitude) float32 ...
    volumetric_soil_water_layer_2                     (latitude, longitude) float32 ...
    volumetric_soil_water_layer_3                     (latitude, longitude) float32 ...
    volumetric_soil_water_layer_4                     (latitude, longitude) float32 ...
    vorticity                                         (level, latitude, longitude) float32 ...
    wind_speed                                        (level, latitude, longitude) float32 ...

In [5]:
from S2S_on_SFNO.Models.sfno.sfnonet import FourierNeuralOperatorNet_Filmed

In [6]:
checkpoint = torch.load("/mnt/qb/work2/goswami0/gkd965/Assets/sfno/weights.tar")
